var vjsSourceList = [];
vjsSourceList.push('src/core')
vjsSourceList.push('src/lib')
vjsSourceList.push('src/json')
vjsSourceList.push('src/player')
vjsSourceList.push('src/controls')
vjsSourceList.push('src/tech')
vjsSourceList.push('src/tracks')
vjsSourceList.push('src/component')
vjsSourceList.push('src/events')
vjsSourceList.push('src/setup')
